# .rubocop.yml

# Set the maximum method length to 20 lines
Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10 

Metrics/BlockLength:
  Max: 30

Style/Documentation:
  Enabled: false