# .rubocop.yml

# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10 

Metrics/BlockLength:
  Max: 30

Style/Documentation:
  Enabled: false